### ISSUE TITLE
Not able to use mopub_flutter: ^1.2.2+1 in ios

### ISSUE THREAD

**Issue by Charlinjoeaht** [arnavvaryani/flutter_advertising_plugins#7]
I tried using mopub_flutter: ^1.2.2+1 in MAC machine and I am getting the following error. Could you please help me resolving this issue

ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Utility/Categories/SKAdImpression+ConvenienceServerResponseInitializer.swift:12:11: error: cannot find type 'SKAdImpression' in scope
    extension SKAdImpression {
              ^~~~~~~~~~~~~~
    ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:113:38: error: cannot find type 'SKAdImpression' in scope
        @objc public var impressionData: SKAdImpression? {
                                         ^~~~~~~~~~~~~~
    ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:88:42: error: cannot find 'SKAdImpression' in scope
                localImpressionDataStorage = SKAdImpression(serverResponse: impressionResponseDictionary) ?? nil
                                             ^~~~~~~~~~~~~~
    ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Utility/Categories/SKAdImpression+ConvenienceServerResponseInitializer.swift:12:11: error: cannot find type 'SKAdImpression' in scope
    extension SKAdImpression {
              ^~~~~~~~~~~~~~
    ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:113:38: error: cannot find type 'SKAdImpression' in scope
        @objc public var impressionData: SKAdImpression? {
                                         ^~~~~~~~~~~~~~
    ios/Pods/mopub-ios-sdk/MoPubSDK/Internal/Common/SKAdNetworkData.swift:88:42: error: cannot find 'SKAdImpression' in scope
                localImpressionDataStorage = SKAdImpression(serverResponse: impressionResponseDictionary) ?? nil

**Comment by NitoBa** [comment]
I have the problem using this package in iOS
